<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `system`;");
E_C("CREATE TABLE `system` (
  `id` enum('1') NOT NULL default '1',
  `value` text,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8");
E_D("replace into `system` values('1','eyJkYiI6eyJob3N0IjoibG9jYWxob3N0IiwidXNlciI6InRndzE3OF90ZyIsInBhc3MiOiJTb3VVRkMzZWk4aCIsIm5hbWUiOiJ0Z3cxNzhfdGcifSwibWVtY2FjaGUiOlsiIiwiIiwiIiwiIl0sIndlYnJvb3QiOm51bGwsInN5c3RlbSI6eyJ3d3dwcmVmaXgiOiJodHRwOlwvXC93d3cuMTc4dGd3LmNvbSIsImltZ3ByZWZpeCI6Imh0dHA6XC9cL3d3dy4xNzh0Z3cuY29tIiwiY3NzcHJlZml4IjoiaHR0cDpcL1wvd3d3LjE3OHRndy5jb20iLCJzaXRlbmFtZSI6IjE3OFx1NTZlMlx1OGQyZFx1N2Y1MSIsInNpdGV0aXRsZSI6Ilx1NTNlZlx1NGVlNVx1OGQ1YVx1OTRiMVx1NzY4NFx1NTZlMlx1OGQyZFx1N2Y1MSIsImFiYnJldmlhdGlvbiI6IjE3OFx1NTZlMlx1OGQyZFx1N2Y1MSIsImNvdXBvbm5hbWUiOiIxNzhcdTRmMThcdTYwZTBcdTUyMzgiLCJjdXJyZW5jeSI6Ilx1MDBhNSIsImN1cnJlbmN5bmFtZSI6IkNOWSIsInRpbWV6b25lIjoiRXRjXC9HTVQtOCIsImluZGV4dGVhbSI6IjUiLCJzaWRldGVhbSI6IjUiLCJlZGl0b3IiOiJraW5kIiwiZGVzY3JpcHRpb24iOiIxNzhcdTU2ZTJcdThkMmRcdTdmNTEiLCJrZXl3b3JkcyI6IjE3OFx1NTZlMlx1OGQyZFx1N2Y1MSIsImludml0ZWNyZWRpdCI6IjAiLCJjb25kdXNlciI6MSwicGFydG5lcmRvd24iOjAsImd6aXAiOjAsImtlZnVxcSI6IjU0NjgwNjQ2MiIsImtlZnVtc24iOiIiLCJtb2JpbGV1cmwiOiJ3d3cuMTc4dGd3LmNvbSIsImljcCI6IiIsInN0YXRjb2RlIjoiIiwic2luYWppd2FpIjoiIiwidGVuY2VudGppd2FpIjoiIn0sImJ1bGxldGluIjp7IjAiOiJcdTUzYmJcdTk4OWRcdTU5MTZcdTcwZWRcdTgyMWVcdTRlMGR2IiwiMiI6IiIsIjEiOiIifSwiYWxpcGF5IjpudWxsLCJ0ZW5wYXkiOm51bGwsInNkb3BheSI6bnVsbCwiYmlsbCI6bnVsbCwiY2hpbmFiYW5rIjpudWxsLCJwYXlwYWwiOm51bGwsInllZXBheSI6bnVsbCwiY21wYXkiOm51bGwsImdvcGF5IjpudWxsLCJvdGhlciI6bnVsbCwib3B0aW9uIjp7ImluZGV4bXVsdGkiOiJZIiwiaW5kZXhwYWdlIjoiWSIsImluZGV4bXVsdGltZWl0dWFuIjoiWSIsInZlcmlmeXJlZ2lzdGVyIjoiWSIsInZlcmlmeXRvcGljIjoiWSIsInZlcmlmeWZlZWRiYWNrIjoiWSIsIm5hdmNvbW1lbnQiOiJZIiwibmF2cHJlZGljdCI6IlkiLCJuYXZwYXJ0bmVyIjoiWSIsIm5hdnNlY29uZHMiOiJZIiwibmF2Z29vZHMiOiJZIiwibmF2Zm9ydW0iOiJZIiwiYnV5Y291cG9uc21zIjoiWSIsInVzZWNvdXBvbnNtcyI6IlkiLCJleHByZXNzYnV5c21zIjoiTiIsImRpc3BsYXlmYWlsdXJlIjoiTiIsInRlYW1hc2siOiJOIiwiY3JlZGl0c2Vjb25kcyI6Ik4iLCJzbXNzdWJzY3JpYmUiOiJOIiwidHJzaW1wbGUiOiJOIiwibW9uZXlzYXZlIjoiWSIsInRlYW13aG9sZSI6Ik4iLCJlbmNvZGVpZCI6IlkiLCJ1c2VycHJpdmFjeSI6IlkiLCJ1c2VyY3JlZGl0IjoiWSIsImNyZWRpdHNob3AiOiJZIiwiY2l0eWxvY2FsIjoiWSIsIm15Y291cG9uIjoiTiIsImJpbmRtb2JpbGUiOiJOIiwiZGF5c2lnbiI6Ik4iLCJ3aWRnZXQiOiJZIiwib25seWNvdXBvbiI6Ik4iLCJpbmRleGNhdGV0ZWFtIjoiWSIsImNhdGV0ZWFtIjoiWSIsImNhdGVwYXJ0bmVyIjoiWSIsImNpdHlwYXJ0bmVyIjoiWSIsImNhdGVzZWNvbmRzIjoiWSIsImNhdGVnb29kcyI6IlkiLCJlbWFpbHZlcmlmeSI6IlkiLCJuZWVkbW9iaWxlIjoiWSIsIm1vYmlsZWNvZGUiOiJZIn0sIm1haWwiOnsiZW5jb2RpbmciOiJVVEYtOCJ9LCJzbXMiOm51bGwsImNyZWRpdCI6bnVsbCwic2tpbiI6eyJ0ZW1wbGF0ZSI6IjU4MjAxMyIsInRoZW1lIjoiWWVsbG93VU1aWiJ9LCJhdXRob3JpemF0aW9uIjpudWxsLCJzaW5hIjpudWxsLCJxcSI6bnVsbCwicXpvbmUiOm51bGx9');");

require("../../inc/footer.php");
?>